server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/files?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

  #设置上传文件的大小
  # max-file-size=10Mb是设置单个文件的大小,
  #max-request-size=100Mb是设置单次请求的文件的总大小
  #如果是想要不限制文件上传的大小，那么就把两个值都设置为-1就行啦
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  # 作用:加载我们的mapper xml文件,用于解决当我们的mapper映射文件所在位置不同于mapper接口所在位置,如果位置相同就可以忽略这条代码
  mapper-locations: classpath:mybatis/mapper/*.xml


files:
  upload:
    path: F:/代码2/小白做毕设2022/files/     #绝对路径

